= How to add Kubernetes users or service accounts

== CONTEXTE

Les *Users* Kubernetes sont typiquement pour des humains, et sont globaux au cluster.

La notion n'existe pas vraiment au niveau Kubernetes, et en fait le concert de User est simplement un certificat signé par le CA du cluster, dont le CN correspond au nom du user.

Comme Kubernetes n'est actuellement pas capable de révoquer un certificat qu'il a signé, cela veut dire que le certificat du user permet de s'authentifier pendant toute sa durée de vie. Il est par contre possible de supprimer les roleBindings associés pour qu'au moins le user n'aie plus de droits.
Les users dans Kubernetes sont plutôt à gérer de façon externe avec un LDAP, SAML, OIDC, ..., et avec un middleware comme par exemple https://github.com/dexidp/dex[Dex] ou https://www.keycloak.org/[Keycloak] pour interfacer Kubernetes avec le fournisseur d'identité.

Les *Service Accounts* sont typiquement pour des pods, et sont spécifiques à un namespace.

Ils sont gérés par Kubernetes et peuvent donc être supprimés, contrairement aux users qui ne peuvent être révoqués.

Ils s'authentifient grâce à un token fourni par Kubernetes


Sources:

* https://github.com/ministryofjustice/cloud-platform/issues/1681#issuecomment-601849367[Kubernetes issue about lack of client cert. revocation support]
* https://github.com/dexidp/dex#dex---a-federated-openid-connect-provider[Dex - A federated OpenID Connect provider]



== HOW TO CREATE SERVICE ACCOUNT

A service account is tied to a namespace, which needs to be created first.

There below is an example for a service account "ecedi" for namespace "owwwuia02":

.Create service account
[source,bash]
----
kubectl create namespace owwwuia02

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecedi
  namespace: owwwuia02
EOF
----


=== How to get service account token

.Check user token name
[source,bash]
----
kubectl describe sa ecedi -n owwwuia02

    # Name:                ecedi
    # Namespace:           owwwuia02
    # Labels:
    # Annotations:         kubectl.kubernetes.io/last-applied-configuration:
    #                     {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"ecedi","namespace":"owwwuia02"}}
    # Image pull secrets:
    # Mountable secrets:   ecedi-token-k9qbl
    # Tokens:              ecedi-token-k9qbl
    # Events:
----

.Get service account token to be used to access Kubernetes on dashboard or through kubectl command line
[source,bash]
----
export NAMESPACE="owwwuia02"
export K8S_USER="ecedi"
kubectl -n ${NAMESPACE} describe secret $(kubectl -n ${NAMESPACE} get secret | (grep ${K8S_USER} || echo "$_") | awk '{print $1}') | grep token: | awk '{print $2}'\n
----

.Get certificate data
[source,bash]
----
kubectl -n ${NAMESPACE} get secret `kubectl -n ${NAMESPACE} get secret | (grep ${K8S_USER} || echo "$_") | awk '{print $1}'` -o "jsonpath={.data['ca\.crt']}"
----


=== Creating kubectl configuration

If you want to configure kubectl with obtained credentials, it will look something like below:

----
$ cat .kube/config

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiB (...)
    server: https://38d9ef62-d708-447d-bc57-8ace867a6418.api.k8s.fr-par.scw.cloud:6443
  name: prod1

contexts:
- context:
    cluster: prod1
    namespace: owwwuia02
    user: ecedi
  name: ecedi-owwwuia02@prod1

current-context: ecedi-owwwuia02@prod1
kind: Config
preferences: {}

users:
- name: ecedi
  user:
    token: eyJhbGciOiJSUzI1NiIsImtp (...)
----


Sources:

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/[Configure Service Accounts for Pods]
* https://computingforgeeks.com/restrict-kubernetes-service-account-users-to-a-namespace-with-rbac/[Create Kubernetes Service / User Account restricted to one Namespace]


=== How to create additional token

NOTE: TODO, see link below

Sources:

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token[Manually create a service account API token]



== HOW TO CREATE USER

Example to create user "ecedi" for cluster "prod2":

[source,bash]
----
# Create user key and CSR
openssl genrsa -out ecedi-prod2.key 2048

openssl req -new -key ecedi-prod2.key -out ecedi-prod2.csr -subj "/CN=ecedi"

# Create CSR resource in Kubernetes, requesting a validity of one day
# usages has to be 'client auth'
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ecedi
spec:
  request: $(cat ecedi-prod2.csr | base64 | tr -d '\n')

  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
  - client auth
EOF

# Get the list of CSRs
kubectl get csr

# Approve the CSR
kubectl certificate approve ecedi

# Get the certificate
kubectl get csr ecedi -o jsonpath='{.status.certificate}'| base64 -d > ecedi-prod2.crt
----

If needed, add the user to Kubeconfig:

[source,bash]
----
kubectl config set-credentials ecedi-prod2 --client-key=ecedi-prod2.key --client-certificate=ecedi-prod2.crt --embed-certs=true
----

Sources:

* https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user[Normal user]
*


== TOOLS TO EXPLORE

* https://github.com/sighupio/permission-manager[Permission Manager]
